name: Code Coverage with Codecov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Updated to v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Updated to v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Dependencies
        run: mvn install -DskipTests

      - name: Run Tests and Generate Coverage
        run: mvn verify

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4 # Updated to v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Codecov token securely stored in GitHub Secrets
          files: ./target/site/jacoco/jacoco.xml # Path to the JaCoCo XML report
          flags: unittests # Optional flag for categorizing coverage
          fail_ci_if_error: true # Fail the workflow if upload fails
          verbose: true # Enable detailed logging
          comment: true # Add a comment to pull requests with coverage details
          commit_parent: true # Ensure association with the pull request commit