name: Code Coverage with Codecov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Dependencies
        run: mvn install -DskipTests

      - name: Run Tests and Generate Coverage
        run: mvn verify

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ c7188293-2338-4633-a4e8-b514e42f71ac }}
          files: ./target/site/jacoco/jacoco.xml
          flags: unittests
          fail_ci_if_error: true