name: Code Coverage with Codecov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Dependencies
        run: mvn install -DskipTests

      - name: Run Tests and Generate Coverage
        run: mvn verify

      - name: Debug Coverage File Path
        run: ls -R ./target/site/jacoco

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: CL1nu5/ChessPlatform
          files: ./target/site/jacoco/jacoco.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true
          comment: true
          commit_parent: true
